### PR TITLE
Oh there are more optional args

### PR DESCRIPTION
**Pull request by sedrubal**
Sorry I didn't see the other optional args yesterday...

### CODE REVIEW

**Comment by seporaitis** [comment]
Thanks! Would you mind adding yourself to [contributors list](https://github.com/seporaitis/poor-smime-sign/blob/master/AUTHORS.rst)?

**Comment by sedrubal** [comment]
Ok, thanks. It's an honour for me :D

**Comment by seporaitis** [comment]
@sedrubal I couldn't find any private means of contact, so I am trying to contact you via a public one.

I need to relicense this project, currently using `GNU Affero GPLv3`, to `MIT License`, which is less restrictive when it comes to use in commercial projects. I am not a legal eagle, but as I have been explained - I need to have an acknowledgement from you before I do this change. Here you have two options: 
- agree with relicensing by replying with a confirmation - and I go and implement it;
- disagree with relicensing, in which case I will be forced to revert your commits, just to avoid any legal issues in the future (unlikely, but I'd rather not put myself into position where they could arise).

For a short summary of the two licenses conditions I found this website helpful: http://choosealicense.com/licenses/

I hope this message reaches you and you can respond within reasonable time, of say a week, but in case it doesn't and in the lack of a different channel of sending a message, I will have to assume the negative answer and revert your contributions, before I do the relicensing. I apologise for that in advance as it sounds harsh, but this is mostly to avoid legal issues down the road.

Best,
Julius

**Comment by sedrubal** [comment]
Sorry for the delay...
I'm OK with `MIT`. Thanks for asking ;)

**Comment by seporaitis** [comment]
Perfect! Thank you very much!

I was on holiday, so all is fine 👍 I will re-license the project this week!

**Pull request merged**
